# Generated by Django 5.1 on 2024-08-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=300)),
                ('estado', models.CharField(choices=[('completado', 'Completado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=100)),
            ],
        ),
    ]
